pipeline:
  name: mytestremote
  identifier: mytestremote
  projectIdentifier: labsproject
  orgIdentifier: abhilabs
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: ShellScript_1
                  identifier: ShellScript_1
                  template:
                    templateRef: pipebrnahc
                    versionLabel: "1"
        tags: {}
