pipeline:
  name: mytestremote
  identifier: mytestremote
  projectIdentifier: labsproject
  orgIdentifier: abhilabs
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo helloa

                          echo <+<+pipeline.variables.someVar>.substring(0,12)>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  variables:
    - name: someVar
      type: String
      description: ""
      required: false
      value: abhisheksahu1234
